### ISSUE TITLE
Font Mastering L1

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/festive#2]
**Diacritics**
- [x] Composite glyphs need to be made out of components using anchors
- [x] Comb.case are missing
- [x] Misaligned diacritics
- [x] Create caron.alt and adjust Lcaron, lcaron, dcaron, tcaron 

**Glyphs**
- [x] Missing glyphs: 0x00A0 (NO-BREAK SPACE), 0x00A4 (CURRENCY SIGN), 0x00AD (SOFT HYPHEN), 0x2074 (SUPERSCRIPT FOUR) and 0x2215 (DIVISION SLASH)
- [x] Add extreme points
- [x] Correct outlines direction

**OT Features**
- [ ] Ensure the OT features include everything and are working well (e.g. fi fl included)

**Comment by crystaltype** [comment]
**Diacritics**
 
 * [ ]  Composite glyphs need to be made out of components using anchors
 * [ ]  Comb.case are missing
 * [ ]  Misaligned diacritics
 * [ ]  Create caron.alt and adjust Lcaron, lcaron, dcaron, tcaron
 
 **Glyphs**
 
* [ ]  Missing glyphs: 0x00A0 (NO-BREAK SPACE), 0x00A4 (CURRENCY SIGN), 0x00AD (SOFT HYPHEN), 0x2074 (SUPERSCRIPT FOUR) and 0x2215 (DIVISION SLASH)
 * [ ]  Add extreme points
* [ ]  Correct outlines direction

 **OT Features**

 * [ ]  Ensure the OT features include everything and are working well (e.g. fi fl included)

**Comment by crystaltype** [comment]
@vv-monsalve

Outlines improvement

Before
<img width="427" alt="Screen Shot 2021-03-31 at 18 34 22" src="https://user-images.githubusercontent.com/20129845/113138378-ea8b4700-924f-11eb-9d8a-918595da9b4b.png">

After
<img width="413" alt="Screen Shot 2021-03-31 at 18 34 37" src="https://user-images.githubusercontent.com/20129845/113138392-ed863780-924f-11eb-91a0-ef4f4f7af2a9.png">

Diacritics
<img width="939" alt="Screen Shot 2021-03-31 at 18 38 51" src="https://user-images.githubusercontent.com/20129845/113138708-5d94bd80-9250-11eb-8120-c2966a456e3d.png">

caron.alt
<img width="187" alt="Screen Shot 2021-03-31 at 18 40 06" src="https://user-images.githubusercontent.com/20129845/113138859-8ae16b80-9250-11eb-97d9-3f787ad0f25f.png">

Missing glyphs
<img width="572" alt="Screen Shot 2021-03-31 at 18 42 08" src="https://user-images.githubusercontent.com/20129845/113139076-d562e800-9250-11eb-8e12-bedead7d699a.png">

**Comment by vv-monsalve** [comment]
@crystaltype Everything looks good here for now. I've merged the latest PR and I'll pull the latest files and see if they produced well the fonts. Confirming beforehand, last time we had thatt [issue on some glyphs](https://github.com/googlefonts/fontmake/issues/755#issuecomment-808185245). Did you solve them in the latest PR?

**Comment by crystaltype** [comment]
> Did you solve them in the latest PR?
Yes I did.

**Comment by vv-monsalve** [comment]
Hi @crystaltype 

I've added the new source and font files that includes the Dingbats into Festive.

In a new [Browser Images issue](https://github.com/googlefonts/festive/issues) I added a homemade comparison gif for the font for you to have as a reference for the diacritics adjustments.

Please check out the thickness of Vietnamese diacritics as some of them look too thin in Windows, particularly `tilde`

Thanks

**Comment by vv-monsalve** [comment]
@crystaltype, there is an error reported when producing the fonts after merging the last PR:
`The following glyph names are referenced but are missing from the glyph set: hookabovecomb.case`

Please check it and solve it. Thanks
